# GeantExascalePilot Travis CI file

language: python

python:
  - "3.6"

services:
  - docker

before_install:
  - docker pull geantx/geantx-dev
  - docker ps -a

install:
  - env
  - mkdir -p ~/.tokens
  - echo "${CTEST_TOKEN}" > ~/.tokens/nersc-cdash
  - export ARGS="--tbb -SF --pyctest-model=Continuous --pyctest-site=Travis -L GeantExascalePilot PTL"
  - OPTIM_FLAGS="--num-tasks=2048 --pyctest-build-type=RelWithDebInfo"
  - DEBUG_FLAGS="--num-tasks=64  --pyctest-build-type=Debug"
  - CMD="python ./pyctest-runner.py ${ARGS} --gperf ${OPTIM_FLAGS}"
  - docker run -it -v ~/.tokens:/root/.tokens -v ${PWD}:/home/geantx geantx/geantx-dev /bin/bash -c "pwd; cd /home/geantx; ${CMD};"
  - CMD="python ./pyctest-runner.py ${ARGS} --coverage ${DEBUG_FLAGS}"
  - docker run -it -v ~/.tokens:/root/.tokens -v ${PWD}:/home/geantx geantx/geantx-dev /bin/bash -c "pwd; cd /home/geantx; ${CMD};"

script:
    - eval "${MATRIX_EVAL}"
